on:
  push:
    paths-ignore:
      - 'README.md'
      - '.github/**'
  pull_request:
    paths-ignore:
      - 'README.md'
      - '.github/**'
  workflow_dispatch:

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
